'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RRAuto.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;ArrayOfConfigLanguage&gt;
        '''  &lt;ConfigLanguage name=&quot;VB.NET&quot; CaseInsensitive=&quot;true&quot; Known=&quot;VBNET&quot; StartComment=&quot;&apos;&quot; TriggersActivators=&quot; .=()&quot;&gt;
        '''    
        '''    &lt;formats&gt;
        '''      &lt;format name=&quot;Text&quot; Font=&quot;Courier New, 10pt&quot; FontColor=&quot;Black&quot; /&gt;
        '''      &lt;format name=&quot;Whitespace&quot; Font=&quot;Courier New, 10pt&quot; FontColor=&quot;Black&quot; /&gt;
        '''      &lt;format name=&quot;KeyWord&quot; Font=&quot;Courier New, 10pt&quot; FontColor=&quot;Blue&quot; /&gt;
        '''      &lt;format name=&quot;String&quot; Font=&quot;Courier New, 10pt&quot; FontColor=&quot;Maroon&quot; /&gt;
        '''      &lt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CodeEditVBConfig() As String
            Get
                Return ResourceManager.GetString("CodeEditVBConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        '''&lt;SandDockLayout Version=&quot;1.4.5.2&quot; IncludeDocuments=&quot;True&quot;&gt;
        '''  &lt;Window Guid=&quot;cc2e8cbd-d720-4a1c-85b4-3d60c20c02be&quot; ContentSize=&quot;225&quot; LastFocused=&quot;-8588966827010091596&quot; DockedContentSize=&quot;255&quot; LastOpenDockSituation=&quot;Docked&quot; LastFixedDockSituation=&quot;Docked&quot; DockedPosition=&quot;Right&quot; LastFloatingWindowGuid=&quot;bcc5b292-b0b0-42f4-9e71-e126492ac7f1&quot; FloatingLocation=&quot;120,206&quot; FloatingSize=&quot;250,370&quot; LastDockContainerCount=&quot;1&quot; LastDockContainerIndex=&quot;0&quot; DockedWorkingSize=&quot;240,180&quot;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DockingDefault() As String
            Get
                Return ResourceManager.GetString("DockingDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Sets a signal based on the state of a given turnout
        '''&apos;The assumption here is that a turnout&apos;s event was bound to this script object
        '''&apos;A reference to that turnout will be passed to &quot;e.Sender&quot; when its bound event is raised 
        '''
        '''Dim objTrack As Track = e.Sender
        '''Dim objSignal as Signal = CtcSignal(&quot;SignalName&quot;)
        '''If objTrack.State.Value = Track.TrackState.Diverging Then
        '''	objSignal.SetAspect(&quot;Caution&quot;)
        '''else
        '''	objSignal.SetAspect(&quot;Clear&quot;)	
        '''End If
        '''.
        '''</summary>
        Friend ReadOnly Property EventScript01() As String
            Get
                Return ResourceManager.GetString("EventScript01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Prevents a route from being unlocked when a sensor is occupied 
        '''&apos;The assumption here is that a route&apos;s &apos;BeforeUnlock&apos; event was bound to this script object
        '''
        '''Dim objSensor As Sensor = CtcSensor(&quot;SensorName&quot;)
        '''If objSensor.State = 1 Then
        '''	&apos;when an attempt is made to unlock the bound route, this cancels that operation
        '''	e.Cancel()
        '''
        '''	PostMsg(&quot;[{0}] could not be unlocked because [{1}] is occupied.&quot;, e.Sender, objSensor)
        '''End If
        '''.
        '''</summary>
        Friend ReadOnly Property EventScript02() As String
            Get
                Return ResourceManager.GetString("EventScript02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Sets a label in the switchboard to display the reported transponder&apos;s locomotive address 
        '''&apos;The assumption here is that a sensor&apos;s event was bound to this script object
        '''
        '''&apos;Check that the packet that triggered this sensor is one capable of reporting 
        '''&apos;transponder information
        '''If Typeof e.Args Is PkMultiSense Then
        '''	&apos;The Loconet packet that triggered the sensor is always returned through e.Args
        '''	Dim objPacket as PkMultiSense = e.Args
        '''
        '''	CtcLabel(&quot;LabelName&quot;).DynamicText = objPacket.DccAddress
        '''End If
        '''.
        '''</summary>
        Friend ReadOnly Property EventScript03() As String
            Get
                Return ResourceManager.GetString("EventScript03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Sub MySubName()
        '''	&apos;Enter code here
        '''End Sub
        '''.
        '''</summary>
        Friend ReadOnly Property GlobalScript01() As String
            Get
                Return ResourceManager.GetString("GlobalScript01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Function MyFuncName() as Object
        '''	&apos;Enter code here
        '''End Function
        '''.
        '''</summary>
        Friend ReadOnly Property GlobalScript02() As String
            Get
                Return ResourceManager.GetString("GlobalScript02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Runtime.CompilerServices.Extension()&gt;
        '''Public Sub MySubName(obj as TypeBeingExtended)
        '''	&apos;Enter code here
        '''End Sub
        '''.
        '''</summary>
        Friend ReadOnly Property GlobalScript03() As String
            Get
                Return ResourceManager.GetString("GlobalScript03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Runtime.CompilerServices.Extension()&gt;
        '''Public Function MyFuncName(obj as TypeBeingExtended) as Object
        '''	&apos;Enter code here
        '''End Function
        '''.
        '''</summary>
        Friend ReadOnly Property GlobalScript04() As String
            Get
                Return ResourceManager.GetString("GlobalScript04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Async Function MyFuncNameAsync() as Task
        '''	&apos;Enter code here
        '''End Function
        '''.
        '''</summary>
        Friend ReadOnly Property GlobalScript05() As String
            Get
                Return ResourceManager.GetString("GlobalScript05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Gets automatically executed when entering operation mode.
        '''&apos;Use &quot;Public Async Sub OnCtcStart()&quot; if sub contains any Awaits.
        '''Public Sub OnCtcStart()
        '''	&apos;Enter code here
        '''End Sub
        '''.
        '''</summary>
        Friend ReadOnly Property GlobalScript06() As String
            Get
                Return ResourceManager.GetString("GlobalScript06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Gets automatically executed when exiting operation mode.
        '''&apos;Use &quot;Public Async Function OnCtcStop() as Task&quot; if method contains any Awaits.
        '''Public Sub OnCtcStop()
        '''	&apos;Enter code here
        '''End Sub
        '''.
        '''</summary>
        Friend ReadOnly Property GlobalScript07() As String
            Get
                Return ResourceManager.GetString("GlobalScript07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Class MyClassName
        '''
        '''	Public Property MyPropName1() as Object
        '''
        '''	Public Property MyPropName2() as Object
        '''
        '''	&apos;Add other properties
        '''
        '''	Public Sub MySubName()
        '''		&apos;Enter code here
        '''	End Sub
        '''
        '''	Public Function MyFuncName() as Object
        '''		&apos;Enter code here
        '''	End Function
        '''
        '''	&apos;Add other methods
        '''
        '''End Class
        '''.
        '''</summary>
        Friend ReadOnly Property GlobalScript08() As String
            Get
                Return ResourceManager.GetString("GlobalScript08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;This is a custom Loconet packet class template
        '''Public Class PkCustom 
        '''	Inherits PkUnknown 
        '''
        '''	Public Sub New() 
        '''		&apos;Initialize a packet with n bytes
        '''		_bytaBytes = New Byte([n-1]) {[byte1],[byte2], ...,[byte n]} 
        '''	End Sub 
        '''
        '''	Public Property MyParameter() As [Type] 
        '''		Get 
        '''			&apos;Decode parameter from _bytaBytes() bytes 
        '''		End Get 
        '''		Set(Value As [Type]) 
        '''			&apos;Encode parameter to _bytaBytes() bytes 
        '''		End Set 
        '''	End Property 
        '''
        '''	Public Overrides ReadOnly Property NeedsPacketResponse() As Boolean         ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GlobalScript09() As String
            Get
                Return ResourceManager.GetString("GlobalScript09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Provides a global variable bag indexed by name
        '''Public Property Var as New VariableBag
        '''.
        '''</summary>
        Friend ReadOnly Property GlobalScript10() As String
            Get
                Return ResourceManager.GetString("GlobalScript10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Posts an arbitrary message to the &quot;CTC Events&quot; pane
        '''PostMsg(&quot;Hello world!!&quot;)
        '''.
        '''</summary>
        Friend ReadOnly Property Snippet01() As String
            Get
                Return ResourceManager.GetString("Snippet01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Check the state of the sensor
        '''If CtcSensor(&quot;SensorName&quot;).State = 1 Then
        '''	&apos;Do stuff when sensor is On
        '''Else
        '''	&apos;Do stuff when sensor is Off
        '''End If
        '''.
        '''</summary>
        Friend ReadOnly Property Snippet02() As String
            Get
                Return ResourceManager.GetString("Snippet02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Set the state of the track and optionally wait for the outcome
        '''If Await CtcTurnout(&quot;TurnoutName&quot;).SetState(&quot;Diverging&quot;) Then
        '''	&apos;Do stuff if setting the state succeeded
        '''Else
        '''	&apos;Do stuff if setting the state failed (possibly due to a lock)
        '''End If
        '''.
        '''</summary>
        Friend ReadOnly Property Snippet03() As String
            Get
                Return ResourceManager.GetString("Snippet03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Get a turnout reference since we will be using it multiple times
        '''Dim objTurnout As Track = CtcTurnout(&quot;TurnoutName&quot;)
        '''
        '''&apos;Optionally you can act based on the turnout&apos;s type
        '''&apos;See documentation of all types defined by the Track.TrackType enumeration
        '''If objTurnout.Type = Track.TrackType.TurnoutDoubleSlip
        '''
        '''	&apos;Check the state of the turnout
        '''	Select Case objTurnout.State.Name
        '''		Case &quot;Cross1&quot;
        '''			&apos;Do stuff when turnout is set to Cross1
        '''		Case &quot;Cross2&quot;, &quot;Diverging1&quot;
        '''			&apos;Do stuff when turnout is set to Cross [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Snippet04() As String
            Get
                Return ResourceManager.GetString("Snippet04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Set the aspect of the signal and optionally wait for the outcome
        '''If Await CtcSignal(&quot;SignalName&quot;).SetAspect(&quot;Clear&quot;) Then
        '''	&apos;Do stuff if setting the aspect succeeded
        '''Else
        '''	&apos;Do stuff if setting the aspect failed
        '''End If
        '''.
        '''</summary>
        Friend ReadOnly Property Snippet05() As String
            Get
                Return ResourceManager.GetString("Snippet05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Get a signal reference since we will be using it multiple times
        '''Dim objSignal as Signal = CtcSignal(&quot;SignalName&quot;)
        '''
        '''&apos;Optionally you can act based on the signals&apos;s aspect configuration
        '''&apos;See documentation of all types defined by the Signal.SignalConfig enumeration
        '''If objSignal.Config = Signal.SignalConfig.StopClearCautionShunt
        '''
        '''	&apos;Check the aspect of the signal
        '''	Select Case objSignal.Aspect.Name
        '''		Case &quot;Stop&quot;
        '''			&apos;Do stuff when signal in showing Stop
        '''		Case &quot;Clear&quot;, &quot;Caution&quot;
        '''			&apos;Do stuff when signa [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Snippet06() As String
            Get
                Return ResourceManager.GetString("Snippet06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Get a route reference since we will be using it multiple times
        '''Dim objRoute as Route = CtcRoute(&quot;RouteName&quot;)
        '''
        '''&apos;Lock the route, wait for it to complete, and act on the result
        '''If Await objRoute.Lock Then 
        '''	&apos;Do stuff if setting the route succeeded
        '''Else
        '''	&apos;Do stuff if setting the route failed
        '''End If 
        '''	
        '''&apos;Same as above, except here we don&apos;t care about the result
        '''Await objRoute.Lock
        '''
        '''&apos;Same as above, except here we don&apos;t even care to wait for
        '''&apos;it to complete before executing the next script line
        '''objR [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Snippet07() As String
            Get
                Return ResourceManager.GetString("Snippet07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Check the state of the route
        '''Select Case CtcRoute(&quot;RouteName&quot;).State
        '''	Case Route.RouteState.Unlocked
        '''		&apos;Do stuff if the route is not locked
        '''	Case Route.RouteState.Pending
        '''		&apos;Do stuff if the route is in the process of being set or locked
        '''	Case Route.RouteState.Locked
        '''		&apos;Do stuff if the route is locked
        '''End Select
        '''.
        '''</summary>
        Friend ReadOnly Property Snippet08() As String
            Get
                Return ResourceManager.GetString("Snippet08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;See documentation for all supported Loconet packet types
        '''
        '''&apos;Check Loconet track power state
        '''Dim objTxPacket as new PkReqSlotData(0)
        '''Await CtcService.LoconetService.TxPacket(objTxPacket)
        '''Dim objRxPacket As PkRdWrSlotData = objTxPacket.RxPacket
        '''PostMsg(objRxPacket.TrackPowerIsOn)
        '''
        '''&apos;Turn Loconet track power on
        '''CtcService.LoconetService.TxPacket(New PkSetPowerOn)
        '''.
        '''</summary>
        Friend ReadOnly Property Snippet09() As String
            Get
                Return ResourceManager.GetString("Snippet09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Get a sequence reference since we will be using it multiple times
        '''Dim objSequence As Sequence = CtcSequence(&quot;SequenceName&quot;)
        '''
        '''&apos;The Play() method returns immediately spawning a new thread
        '''If objSequence.Play() then
        '''	PostMsg(&quot;Sequence is now playing.&quot;)
        '''Else
        '''	PostMsg(&quot;Sequence is already playing or recording.&quot;)
        '''End If
        '''
        '''&apos;The sequence can later be stopped from this or other scripts
        '''objSequence.Stop()
        '''.
        '''</summary>
        Friend ReadOnly Property Snippet10() As String
            Get
                Return ResourceManager.GetString("Snippet10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Get an engine reference since we will be using it multiple times
        '''Dim objEngine As Engine = CtcBoundEngine(&quot;EngineName&quot;)
        '''
        '''&apos;If the given engine is not bound to a slot, an error will be reported
        '''&apos;You can set the engine&apos;s AutoBindInOpr property to True so binding occurs 
        '''&apos;automaticaly when entering operation mode
        '''
        '''&apos;Set the engine&apos;s direction forward
        '''objEngine.Direction = LocoDirection.Forward
        '''
        '''&apos;Turn on the engine&apos;s lights 
        '''objEngine.Functions(0) = 1
        '''
        '''&apos;Start a smooth speed ramp from the current spe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Snippet11() As String
            Get
                Return ResourceManager.GetString("Snippet11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PostMsg(&quot;Script started.&quot;)
        '''
        '''&apos;Waits for 3000ms (3sec) before continuing to the next line
        '''Await Delay(3000)
        '''
        '''PostMsg(&quot;Script ended after a 3 second delay.&quot;)
        '''.
        '''</summary>
        Friend ReadOnly Property Snippet12() As String
            Get
                Return ResourceManager.GetString("Snippet12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PostMsg(&quot;Script started.&quot;)
        '''
        '''&apos;Waits for either either &quot;Sensor1&quot; or &quot;Sensor2&quot; to report an &apos;On&apos; state
        '''&apos;before continuing to the next line.
        '''Await OnEvent(New EventsList() FROM {
        '''	{CtcSensor(&quot;Sensor1&quot;), &quot;StateReported&quot;}, 
        '''	{CtcSensor(&quot;Sensor2&quot;), &quot;StateReported&quot;}},
        '''	Function(ea)
        '''		&apos;ea.Sender always returns the object that raised the event
        '''		&apos;In this case it can only be one of the two sensors specified above
        '''
        '''		&apos;Check to see if the sensor that raised the event satisfies our condition
        '''		If ea.Sender.St [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Snippet13() As String
            Get
                Return ResourceManager.GetString("Snippet13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PostMsg(&quot;Starting count down&quot;)
        '''
        '''Await Delay(1000)
        '''For intCnt as Integer = 10 to 1 step -1
        '''	PostMsg(intCnt)
        '''	Await Delay(1000)
        '''Next
        '''
        '''PostMsg(&quot;Blast off&quot;)
        '''.
        '''</summary>
        Friend ReadOnly Property Snippet14() As String
            Get
                Return ResourceManager.GetString("Snippet14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Plays a sound file asynchronously from a given directory at half volume
        '''PlaySound(&quot;C:\Users\Perry\Documents\Sounds\MySound.wav&quot;, 0.5)
        '''.
        '''</summary>
        Friend ReadOnly Property Snippet15() As String
            Get
                Return ResourceManager.GetString("Snippet15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Get a script reference since we will be using it multiple times
        '''Dim objScript as StepScript = CtcStepScript(&quot;ScriptName&quot;)
        '''
        '''&apos;Starts a step script from the beginning
        '''&apos;Await is optional if you want to wait for it to complete
        '''&apos;before executing the next line
        '''Await objScript.StartAt(0)
        '''
        '''&apos;The script can later be stopped from this or other scripts
        '''objScript.Stop()
        '''
        '''&apos;Assuming the script is stopped, resume from last location
        '''Await objScript.StartAt(objScript.StepPos)
        '''.
        '''</summary>
        Friend ReadOnly Property Snippet16() As String
            Get
                Return ResourceManager.GetString("Snippet16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''    &lt;head&gt;
        '''        &lt;title&gt;Speech Gammar Help&lt;/title&gt;
        '''        &lt;style type=&quot;text/css&quot;&gt;
        '''            body {
        '''	            margin: 0px;
        '''	            padding: 10px;
        '''            }
        '''            .Title{
        '''				color: #000080;
        '''				font-weight: bold;
        '''				font-size: 15px;
        '''				font-family: Arial;
        '''				padding-left: 2;
        '''				padding-right: 2;
        '''				font-style: italic;
        '''				margin-bottom: 3;
        '''			}
        '''			.Speech	{
        '''				color: red;
        '''	            font-weight: normal;
        '''	            font-size: 13px;
        '''	            fon [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SpeechGrammar() As String
            Get
                Return ResourceManager.GetString("SpeechGrammar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;These single line steps are not awaited by the caller because they don&apos;t return Task objects.
        '''
        '''&apos;PostMsg() is not awaitable because it does not return a Task.
        '''o.Step(&quot;StepName1&quot;, Sub() PostMsg(&quot;Executing&quot;))
        '''
        '''&apos;Delay() returns a Task but since this step uses a Sub() no Task is returned.
        '''o.Step(&quot;StepName2&quot;, Sub() Delay(1000))
        '''.
        '''</summary>
        Friend ReadOnly Property StepScript01() As String
            Get
                Return ResourceManager.GetString("StepScript01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;This single line step is awaited by the caller because Delay() returns a Task and 
        '''&apos;the step in turn returns that task through the Function()
        '''o.Step(&quot;StepName&quot;, Function() Delay(1000))
        '''.
        '''</summary>
        Friend ReadOnly Property StepScript02() As String
            Get
                Return ResourceManager.GetString("StepScript02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;These multi-line steps are not awaited by the caller because they don&apos;t return Task objects.
        '''
        '''&apos;This step contains nothing that can be awaited.
        '''o.Step(&quot;StepName1&quot;, Sub()
        '''	If CtcSensor(&quot;SensorName&quot;).State = 1 Then
        '''		PostMsg(&quot;Executing&quot;)
        '''	End If
        '''End Sub)
        '''
        '''&apos;This step contains some internal awaits but the step returns no Task so the caller will not await it.
        '''&apos;The &quot;Async&quot; declaration is required if any of the containing methods are awaited.
        '''o.Step(&quot;StepName2&quot;, Async Sub()
        '''	Await Delay(1000)
        '''	PostMsg [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property StepScript03() As String
            Get
                Return ResourceManager.GetString("StepScript03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;These multi-line steps are awaited by the caller because they return a Task.
        '''
        '''&apos;The &quot;Async&quot; key word wraps the entire step into a Task and returns it.
        '''&apos;The &quot;Async&quot; declaration is required if any of the containing methods are Awaited.
        '''o.Step(&quot;StepName1&quot;, Async Function()
        '''	Await Delay(1000)
        '''	PostMsg(&quot;Executing 1&quot;)
        '''	Await Delay(1000)
        '''	PostMsg(&quot;Executing 2&quot;)
        '''End Function)
        '''
        '''&apos;No &quot;Async&quot; is needed here because the only awaitable method is at the end
        '''&apos;so that task can be returned directly. Note that thi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property StepScript04() As String
            Get
                Return ResourceManager.GetString("StepScript04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;The cancel token, provided by the step script (o)bject, can be passed into any
        '''&apos;long running task, that accepts a cancellation token, so that it can be aborted
        '''&apos;immediately and gracefully when the step script is given a stop order.
        '''o.Step(&quot;StepName&quot;, Function()
        '''	PostMsg(&quot;Starting long running task&quot;)
        '''	Return Delay(100000, o.CancelToken)
        '''End Function)
        '''.
        '''</summary>
        Friend ReadOnly Property StepScript05() As String
            Get
                Return ResourceManager.GetString("StepScript05", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
