'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property ComPort() As Byte
        Get
            Return CType(Me("ComPort"),Byte)
        End Get
        Set
            Me("ComPort") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("_57600")>  _
    Public Property BaudRate() As Global.RRAutoLib.Loconet.BaudRate
        Get
            Return CType(Me("BaudRate"),Global.RRAutoLib.Loconet.BaudRate)
        End Get
        Set
            Me("BaudRate") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property FlowControl() As Boolean
        Get
            Return CType(Me("FlowControl"),Boolean)
        End Get
        Set
            Me("FlowControl") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property LoadLastFile() As Boolean
        Get
            Return CType(Me("LoadLastFile"),Boolean)
        End Get
        Set
            Me("LoadLastFile") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property LastFileUsed() As String
        Get
            Return CType(Me("LastFileUsed"),String)
        End Get
        Set
            Me("LastFileUsed") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property LastModeUsed() As Global.RRAuto.AppMode
        Get
            Return CType(Me("LastModeUsed"),Global.RRAuto.AppMode)
        End Get
        Set
            Me("LastModeUsed") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property SpeechService() As Boolean
        Get
            Return CType(Me("SpeechService"),Boolean)
        End Get
        Set
            Me("SpeechService") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property VoiceFeedback() As Boolean
        Get
            Return CType(Me("VoiceFeedback"),Boolean)
        End Get
        Set
            Me("VoiceFeedback") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property LoconetShowStamp() As Boolean
        Get
            Return CType(Me("LoconetShowStamp"),Boolean)
        End Get
        Set
            Me("LoconetShowStamp") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property LoconetShowSource() As Boolean
        Get
            Return CType(Me("LoconetShowSource"),Boolean)
        End Get
        Set
            Me("LoconetShowSource") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property LoconetShowDesc() As Boolean
        Get
            Return CType(Me("LoconetShowDesc"),Boolean)
        End Get
        Set
            Me("LoconetShowDesc") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property LoconetShowParm() As Boolean
        Get
            Return CType(Me("LoconetShowParm"),Boolean)
        End Get
        Set
            Me("LoconetShowParm") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property LoconetShowOpCode() As Boolean
        Get
            Return CType(Me("LoconetShowOpCode"),Boolean)
        End Get
        Set
            Me("LoconetShowOpCode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property LoconetShowHex() As Boolean
        Get
            Return CType(Me("LoconetShowHex"),Boolean)
        End Get
        Set
            Me("LoconetShowHex") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property LoconetShowID() As Boolean
        Get
            Return CType(Me("LoconetShowID"),Boolean)
        End Get
        Set
            Me("LoconetShowID") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("500")>  _
    Public Property ListMaxLines() As UShort
        Get
            Return CType(Me("ListMaxLines"),UShort)
        End Get
        Set
            Me("ListMaxLines") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property DefaultZoomLevel() As Double
        Get
            Return CType(Me("DefaultZoomLevel"),Double)
        End Get
        Set
            Me("DefaultZoomLevel") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
    Public Property ZoomIncrement() As Byte
        Get
            Return CType(Me("ZoomIncrement"),Byte)
        End Get
        Set
            Me("ZoomIncrement") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FF2F4F4F")>  _
    Public Property BackColor() As Global.System.Windows.Media.Color
        Get
            Return CType(Me("BackColor"),Global.System.Windows.Media.Color)
        End Get
        Set
            Me("BackColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FF008B8B")>  _
    Public Property GridColor() As Global.System.Windows.Media.Color
        Get
            Return CType(Me("GridColor"),Global.System.Windows.Media.Color)
        End Get
        Set
            Me("GridColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FFFF0000")>  _
    Public Property TurnoutLockedColor() As Global.System.Windows.Media.Color
        Get
            Return CType(Me("TurnoutLockedColor"),Global.System.Windows.Media.Color)
        End Get
        Set
            Me("TurnoutLockedColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FFFFFF00")>  _
    Public Property TurnoutPendingColor() As Global.System.Windows.Media.Color
        Get
            Return CType(Me("TurnoutPendingColor"),Global.System.Windows.Media.Color)
        End Get
        Set
            Me("TurnoutPendingColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FFFF8000")>  _
    Public Property TurnoutSetColor() As Global.System.Windows.Media.Color
        Get
            Return CType(Me("TurnoutSetColor"),Global.System.Windows.Media.Color)
        End Get
        Set
            Me("TurnoutSetColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FFA0A0A0")>  _
    Public Property FreeBlockColor() As Global.System.Windows.Media.Color
        Get
            Return CType(Me("FreeBlockColor"),Global.System.Windows.Media.Color)
        End Get
        Set
            Me("FreeBlockColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FFEEE8AA")>  _
    Public Property ResBlockColor() As Global.System.Windows.Media.Color
        Get
            Return CType(Me("ResBlockColor"),Global.System.Windows.Media.Color)
        End Get
        Set
            Me("ResBlockColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FFFFD700")>  _
    Public Property ResOccBlockColor() As Global.System.Windows.Media.Color
        Get
            Return CType(Me("ResOccBlockColor"),Global.System.Windows.Media.Color)
        End Get
        Set
            Me("ResOccBlockColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FFF08080")>  _
    Public Property OccBlockColor() As Global.System.Windows.Media.Color
        Get
            Return CType(Me("OccBlockColor"),Global.System.Windows.Media.Color)
        End Get
        Set
            Me("OccBlockColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")>  _
    Public Property SelectionColor() As Global.System.Windows.Media.Color
        Get
            Return CType(Me("SelectionColor"),Global.System.Windows.Media.Color)
        End Get
        Set
            Me("SelectionColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property RecentDocuments() As Global.System.Collections.ArrayList
        Get
            Return CType(Me("RecentDocuments"),Global.System.Collections.ArrayList)
        End Get
        Set
            Me("RecentDocuments") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property SimulationMode() As Boolean
        Get
            Return CType(Me("SimulationMode"),Boolean)
        End Get
        Set
            Me("SimulationMode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property CtcEventsShowNative() As Boolean
        Get
            Return CType(Me("CtcEventsShowNative"),Boolean)
        End Get
        Set
            Me("CtcEventsShowNative") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property CtcEventsShowUser() As Boolean
        Get
            Return CType(Me("CtcEventsShowUser"),Boolean)
        End Get
        Set
            Me("CtcEventsShowUser") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property EnableRemServ() As Boolean
        Get
            Return CType(Me("EnableRemServ"),Boolean)
        End Get
        Set
            Me("EnableRemServ") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("8080")>  _
    Public Property RemServPort() As UShort
        Get
            Return CType(Me("RemServPort"),UShort)
        End Get
        Set
            Me("RemServPort") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("#FFF08080")>  _
    Public Property TrackNoBlockColor() As Global.System.Windows.Media.Color
        Get
            Return CType(Me("TrackNoBlockColor"),Global.System.Windows.Media.Color)
        End Get
        Set
            Me("TrackNoBlockColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ForceSetState() As Boolean
        Get
            Return CType(Me("ForceSetState"),Boolean)
        End Get
        Set
            Me("ForceSetState") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property BroadcastStates() As Boolean
        Get
            Return CType(Me("BroadcastStates"),Boolean)
        End Get
        Set
            Me("BroadcastStates") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property QuerySensors() As Boolean
        Get
            Return CType(Me("QuerySensors"),Boolean)
        End Get
        Set
            Me("QuerySensors") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("false")>  _
    Public Property ClearCtcEvents() As String
        Get
            Return CType(Me("ClearCtcEvents"),String)
        End Get
        Set
            Me("ClearCtcEvents") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.RRAuto.MySettings
            Get
                Return Global.RRAuto.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
